In [1]:
from sklearn.feature_selection import chi2
import pandas as pd

df = pd.read_csv('../csv/balanced_data_label_encoded.csv')

In [3]:
X = df.drop(columns=['track_id', 'genre'])
X

# chi2(X=X, y=df['genre'])

,duration,end_of_fade_in,key,key_confidence,loudness,mode,mode_confidence,start_of_fade_out,tempo,time_signature,time_signature_confidence
0,185.78240,0.352,11,0.698,-10.316,1,0.650,175.177,101.040,4,1.000
1,208.14322,0.259,0,0.717,-5.384,1,0.675,199.262,140.595,4,0.463
2,227.57832,2.682,0,0.463,-7.695,0,0.498,216.474,96.068,4,0.463
3,138.42240,0.125,9,0.609,-4.994,0,0.357,132.737,201.951,4,0.286
4,197.06730,0.293,9,0.000,-20.832,1,0.132,189.684,116.539,4,1.000
...,...,...,...,...,...,...,...,...,...,...,...
1849,399.88200,3.663,3,1.000,-10.648,1,0.548,394.043,85.399,4,0.430
1850,368.11710,0.496,9,0.850,-12.157,1,0.562,351.539,58.387,4,0.572
1851,175.25506,0.000,4,0.582,-11.951,1,0.345,175.255,152.942,4,0.492
1852,262.97424,0.165,5,0.312,-8.737,1,0.152,256.935,80.031,4,0.000
1853,164.54485,0.000,6,0.195,-10.897,1,0.501,154.912,148.045,4,0.000